---
title: "Data Science HW5"
author: "Boya Guo"
date: "11/9/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(echo = TRUE,
                      fig.width = 6,
                      fig.asp = .6,
                      out.width = "90%")
theme_set(theme_bw() + 
  theme(legend.position = "bottom"))
```


```{r p1.1:read in data}
read_csv_data = function(x) {
  
  read_csv(x) %>% 
    mutate(name = x)
}

file_list = list.files("./data/") %>% paste0("./data/", .)

```

```{r p1.2: tidying data}
hw5 = map_dfr(file_list, read_csv_data) %>%
  mutate(arm = ifelse(str_detect(name, "con") == TRUE, "control", "experimental"),
         subject_id = substr(name, 12, 13)) %>% 
  gather(key = week, value = observation, week_1:week_8) %>% 
  mutate(week = str_replace(week, "week_", ""),
         id = as.factor(subject_id),
         week = as.numeric(week)) %>% 
  select(id, arm, week, observation) %>% 
  janitor::clean_names()

hw5
```

```{r p1.3: spaghetti plot}
  ggplot(hw5,aes(x = week, y = observation, color = id)) + 
  geom_line() +
  facet_grid(.~ arm) +
    labs(
    title = "The change of observations across time in the control and experimental arms" ,
    x = "Weeks" ,
    y = "Observations"
    ) +
  theme(legend.position = "left")
```

According to the plot produced, we could find that there is an increase in the observations of experimental groups as time increases. However, the change in the control group seems to fluctuate between -1.25 and 3.75, with no apparent change as time increases.

